<?php $data = $block->getList(); ?>
<?php if($data): ?>
<div class="table-wrapper downloadable-products">
    <table id="my-downloadable-products-table" class="data table table-downloadable-products">
        <caption class="table-caption"><?php echo __('List Event') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col title"><?php echo __('Date') ?></th>
            <th scope="col" class="col title"><?php echo __('Code') ?></th>
            <th scope="col" class="col title"><?php echo __('Balance') ?></th>
            <th scope="col" class="col title"><?php echo __('Action') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($data as $item): ?>
            <tr>
                <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col title">
                    <?php echo $item['action_time'] ?>
                </td>
                <td data-th="<?php echo $block->escapeHtml(__('Code')) ?>" class="col title">
                    <?php echo $item['code'] ?>
                </td>
                <td data-th="<?php echo $block->escapeHtml(__('Balance')) ?>" class="col title">
                    <?php echo __('$').$item['balance'] ?>
                </td>
                <td data-th="<?php echo $block->escapeHtml(__('Action')) ?>" class="col title">
                    <?php echo $item['action'] ?>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div>
<?php endif; ?>
